@startuml
'https://plantuml.com/sequence-diagram

autonumber

MovieService -> ApiService: getApiDataWithMapper(buildDiscoverUrl(year, currentPage), objectMapper)
ApiService -> MovieService: JsonNode(parseMovies(response))
MovieService -> ApiService: getApiDataWithMapper(url, objectMapper)
ApiService -> MovieService: JsonNode(response)



@enduml